[pyprland]
plugins = [
 "expose",
 "fetch_client_menu",
 "lost_windows",
 "magnify",
 "scratchpads",
 "shift_monitors",
 "toggle_special",
 "workspaces_follow_focus",
]

# using variables for demonstration purposes (not needed)
[pyprland.variables]
term_classed = "kitty --class"

[scratchpads.term]
animation = "fromTop"
command = "[term_classed] main-dropterm"
class = "main-dropterm"
# size = "98% 90%"
# max_size = "1920px 100%"
unfocus = "hide"
margin = 50
lazy = trueV

[scratchpads.volume]
command = "pavucontrol"
animation = "fromRight"
lazy = true
size = "40% 40%"
unfocus = "hide"